#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


cd ~/Desktop/F1car/constant/triSurface/
rm ADD1.stl
rm ADD2.stl
rm ADD3.stl
rm ADDFINAL.stl
cd ~/Desktop/F1car/

cleanCase

rm ADDFINALwithbox.stl
rm ADDFINALwithbox.fms
#cleanExplicitFeatures

#------------------------------------------------------------------------------
